# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Run My Python App 

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install os
        pip install requests  
        pip install python-dotenv

    - name: Set up GitHub Token as environment variable
      run: echo "USER_GITHUB_TOKEN=${{ secrets.USER_GITHUB_TOKEN }}" >> $GITHUB_ENV
            
    - name: Run my python app
      run: |
        python main.py
